spring:
  application:
    name: concert-api

  data:
    mongodb:
      host: localhost
      port: 27017
      database: concert

  cache:
    type: caffeine
    cache-names: concert, concert-list
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=1h

server:
  port: 8082

logging:
  level:
    com.concertticketing: INFO
